server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/supportportal?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
